### ISSUE TITLE
Homepage: Banner text should be placed/positioned the same from the design.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Brittons-Formal-Wear#20]
![image](https://cloud.githubusercontent.com/assets/13363508/8793999/d5e70b16-2fb0-11e5-8807-498b2e589f76.png)

**Comment by genesiscebudigital** [comment]
the Height of the banner is not consistent . , we can't make it 100% align

**Comment by maehtitan** [comment]
I am not referring to the banner height, it's the position of the text, have it move to the left side and align before the letter "r" from word "for" just like the design

**Comment by maehtitan** [comment]
Still not aligned

![image](https://cloud.githubusercontent.com/assets/13363508/9003520/53d9e550-37a1-11e5-9711-5296af83d012.png)

**Comment by genesiscebudigital** [comment]
it is percentage . , We already had a meeting with jolene that as long it will not affect the functionality and looks like almost the design.

**Comment by maehtitan** [comment]
Why not make it 64% instead of 66% to achieve the design? 
![image](https://cloud.githubusercontent.com/assets/13363508/9031453/bbeefd88-39e5-11e5-9e7d-827743d0db62.png)

**Comment by genesiscebudigital** [comment]
it's ok in my end  . , i think the width of my screen is different to your screen . , but i will make it 64% to make this bug done.
