### ISSUE TITLE
Homepage - Mobile: The social media icons shouldn't be part of the collapsible menu, it should be separated just like the ipad view but add it before the menu layout not below and pls make it center-align

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Brittons-Formal-Wear#24]
Devices: Itouch 5 and S4 (portrait and landscape)

![image](https://cloud.githubusercontent.com/assets/13363508/8794561/4c2fa4f8-2fb7-11e5-88ef-279759fd78eb.png)

**Comment by maehtitan** [comment]
The icons still not center-align

![image](https://cloud.githubusercontent.com/assets/13363508/8973722/067da870-369b-11e5-8120-0ae674dd55b9.png)

**Comment by genesiscebudigital** [comment]
this not a bug because there is no psd for this

**Comment by maehtitan** [comment]
But you can make it consistent just like the ipad view

**Comment by genesiscebudigital** [comment]
right is enough . , if i will put it to the center . , will conver the home and the menu button if the width will reduce . , i hope you can relate

**Comment by maehtitan** [comment]
Why not move the navigation menu down, so that it will not affect the other layout.

![image](https://cloud.githubusercontent.com/assets/13363508/9031623/da5585b0-39e7-11e5-843b-3cc1a51daea8.png)
