### ISSUE TITLE
Suit Hire Single View: Based from the design there are 2 images displayed, without the 2nd image will create a big space gap next to the first image

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Brittons-Formal-Wear#27]
![image](https://cloud.githubusercontent.com/assets/13363508/8795635/18842d4a-2fc1-11e5-95ab-62e5b772c34c.png)

**Comment by genesiscebudigital** [comment]
there is only one featured image in the project scope

**Comment by maehtitan** [comment]
If that's the case we need to expand the image to fit the empty spaces on the right side and also allow 4 images for the related suits so that it will align the image above it

![image](https://cloud.githubusercontent.com/assets/13363508/8974114/afce550a-36a0-11e5-930a-d9a4f33cf776.png)

**Comment by genesiscebudigital** [comment]
ok i will make the image width to 100% but we need to suggest the client  that they will upload larger image so that it will not stretch. like this
http://brittonsformalwear.stage.titanweb.com.au/products/classic/title-of-suit-goes-here-3/

**Comment by genesiscebudigital** [comment]
that's is already allow 4 related items . , it only shows 2 because the related items is less than 4

**Comment by maehtitan** [comment]
While running through all the pages i noticed that...
width: 100% is not advisable in featured image since it will stretch the small image uploaded, you can use the bootstrap class="img-responsive" for alternative, it's fine if the image goes small and doesn't fit the whole image container as long as it's not pixelated.
