### ISSUE TITLE
Suit Hire Single View: Instagram icon is missing.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Brittons-Formal-Wear#28]
![image](https://cloud.githubusercontent.com/assets/13363508/8795697/9fdfd14a-2fc1-11e5-8e7e-a8a41b97878c.png)

**Comment by genesiscebudigital** [comment]
We still waiting from titan's clarification because the plugin they provide has no instagram

**Comment by maehtitan** [comment]
We'll marked this one as fixed when you have feedback already.
