### ISSUE TITLE
Gallery: The pagination works as one for different galleries, for ex: when I navigate the next page from the first gallery, the second gallery below also navigate itself, and when I try to jump on the 4th page the first gallery disappears.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Brittons-Formal-Wear#33]
![image](https://cloud.githubusercontent.com/assets/13363508/8955082/74268da8-361c-11e5-9a71-c1698c7fd9e6.png)

**Comment by genesiscebudigital** [comment]
Because the first gallery has no page 4 . , that is the behavior of nextgen gallery . , I don't want to touch the core of that plugin  because if the client update the plugin . , all of my changes will gone
