### ISSUE TITLE
Homepage - Mobile: Banner text should be right aligned just like desktop view / design given

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Brittons-Formal-Wear#34]
Ipod Touch 5

![image](https://cloud.githubusercontent.com/assets/13363508/8974496/cfc05c7e-36a4-11e5-853d-017b3c13c9d9.png)

**Comment by maehtitan** [comment]
Still left aligned in landscape view

**Comment by genesiscebudigital** [comment]
I will put it to the center because if i will align it to the right. , the button will also align to right.
