### ISSUE TITLE
Homepage - Mobile: Banner text should be right aligned just like the desktop view

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Brittons-Formal-Wear#35]
Device: S4
![image](https://cloud.githubusercontent.com/assets/13363508/8973666/3996632e-369a-11e5-84a5-c84daaa187ab.png)

**Comment by maehtitan** [comment]
Still left aligned in landscape view

**Comment by genesiscebudigital** [comment]
I will put it to the center because if i will align it to the right. , the button will also align to right.
