### ISSUE TITLE
News - Mobile: Please center align the sidebar

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Brittons-Formal-Wear#41]
Devices: 
Itouch (landscape)
S4 (landscape)
Ipad Air (portrait & landscape)

**Comment by maehtitan** [comment]
Not yet centered

**Comment by genesiscebudigital** [comment]
it's center already . ,or please provide screen sot

**Comment by maehtitan** [comment]
This is the actual devices screenshot from Ipad: 

Portrait
![image](https://cloud.githubusercontent.com/assets/13363508/9032444/49450a5a-39f1-11e5-91d8-60d0ec39b00b.png)

Landscape

![image](https://cloud.githubusercontent.com/assets/13363508/9032450/58659518-39f1-11e5-9530-1ecfebd24f1b.png)
