### ISSUE TITLE
Gallery: W3C checking - 26 errors

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Brittons-Formal-Wear#43]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fbrittonsformalwear.stage.titanweb.com.au%2Fgallery%2F

**Comment by genesiscebudigital** [comment]
it's because there are 2 galleries in 1 page . , you can use album instead of two galleries . , the ID was duplicated . , I will not touch the core of the plugin
