### ISSUE TITLE
Admin - Custom Tailoring: Incorrect template used

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Brittons-Formal-Wear#52]
Apply fixes also to the following pages below:
Frequently Asked Questions
Gallery
News
Online Fitting

![image](https://cloud.githubusercontent.com/assets/13363508/9082072/1a049018-3b94-11e5-9118-6d5e24747336.png)

**Comment by maehtitan** [comment]
Apply fixes also to the following pages below:
Frequently Asked Questions
Gallery
News
Online Fitting

**Comment by hctire** [comment]
Still using the Default template the ff pages below:
Frequently Asked Questions
Gallery
News

**Comment by maehtitan** [comment]
Still uses the Default Template of the ff pages below:
Frequently Asked Questions
Gallery
News
