### ISSUE TITLE
Contact Us: The Sunday Opening Hours supposed to be closed based from the design.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Brittons-Formal-Wear#6]
![image](https://cloud.githubusercontent.com/assets/13363508/8769634/b8fbc376-2ed3-11e5-96af-6d595b1a88ed.png)

which schedule we should follow? Is it the header section or the contact us page?

**Comment by genesiscebudigital** [comment]
this is not nessesary because the client can edit it
![contact](https://cloud.githubusercontent.com/assets/11186352/8925457/76df3ffa-353a-11e5-9f2a-5a065de67b94.png)
